name: Generate Snake Animation

on:
  # Run automatically every day
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Optional: commit and push the generated files
      - uses: actions/checkout@v3
      
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate snake animation'
          add: 'dist'
